import React from "react";
import {
  TotalMediaWraper,
  TotalMediaText,
  MediaList,
  MediaCard,
  MediaDivider,
  MediaTime,
  MediaTitle,
  MediaLikeIcon,
  MediaLikeText,
  MediaCommentIcon,
  MediaCommentText,
} from "../../styles/media/TotalMedia.style";

export default function TotalMedia() {
  return (
    <TotalMediaWraper>
      <TotalMediaText>전체 미디어</TotalMediaText>
      <MediaList>
        <MediaCard>
          <MediaTitle>aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa</MediaTitle>
          <MediaTime>10:10</MediaTime>
          <MediaDivider></MediaDivider>
          <MediaLikeIcon></MediaLikeIcon>
          <MediaLikeText>1000</MediaLikeText>
          <MediaCommentIcon></MediaCommentIcon>
          <MediaCommentText>112</MediaCommentText>
        </MediaCard>
        <MediaCard>
          <MediaTitle>aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa</MediaTitle>
          <MediaTime>10:10</MediaTime>
          <MediaDivider></MediaDivider>
          <MediaLikeIcon></MediaLikeIcon>
          <MediaLikeText>1000</MediaLikeText>
          <MediaCommentIcon></MediaCommentIcon>
          <MediaCommentText>112</MediaCommentText>
        </MediaCard>
        <MediaCard>
          <MediaTitle>aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa</MediaTitle>
          <MediaTime>10:10</MediaTime>
          <MediaDivider></MediaDivider>
          <MediaLikeIcon></MediaLikeIcon>
          <MediaLikeText>1000</MediaLikeText>
          <MediaCommentIcon></MediaCommentIcon>
          <MediaCommentText>112</MediaCommentText>
        </MediaCard>
        <MediaCard>
          <MediaTitle>aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa</MediaTitle>
          <MediaTime>10:10</MediaTime>
          <MediaDivider></MediaDivider>
          <MediaLikeIcon></MediaLikeIcon>
          <MediaLikeText>1000</MediaLikeText>
          <MediaCommentIcon></MediaCommentIcon>
          <MediaCommentText>112</MediaCommentText>
        </MediaCard>
        <MediaCard>
          <MediaTitle>aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa</MediaTitle>
          <MediaTime>10:10</MediaTime>
          <MediaDivider></MediaDivider>
          <MediaLikeIcon></MediaLikeIcon>
          <MediaLikeText>1000</MediaLikeText>
          <MediaCommentIcon></MediaCommentIcon>
          <MediaCommentText>112</MediaCommentText>
        </MediaCard>
        <MediaCard>
          <MediaTitle>aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa</MediaTitle>
          <MediaTime>10:10</MediaTime>
          <MediaDivider></MediaDivider>
          <MediaLikeIcon></MediaLikeIcon>
          <MediaLikeText>1000</MediaLikeText>
          <MediaCommentIcon></MediaCommentIcon>
          <MediaCommentText>112</MediaCommentText>
        </MediaCard>
        <MediaCard>
          <MediaTitle>aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa</MediaTitle>
          <MediaTime>10:10</MediaTime>
          <MediaDivider></MediaDivider>
          <MediaLikeIcon></MediaLikeIcon>
          <MediaLikeText>1000</MediaLikeText>
          <MediaCommentIcon></MediaCommentIcon>
          <MediaCommentText>112</MediaCommentText>
        </MediaCard>
        <MediaCard>
          <MediaTitle>aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa</MediaTitle>
          <MediaTime>10:10</MediaTime>
          <MediaDivider></MediaDivider>
          <MediaLikeIcon></MediaLikeIcon>
          <MediaLikeText>1000</MediaLikeText>
          <MediaCommentIcon></MediaCommentIcon>
          <MediaCommentText>112</MediaCommentText>
        </MediaCard>
        <MediaCard>
          <MediaTitle>aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa</MediaTitle>
          <MediaTime>10:10</MediaTime>
          <MediaDivider></MediaDivider>
          <MediaLikeIcon></MediaLikeIcon>
          <MediaLikeText>1000</MediaLikeText>
          <MediaCommentIcon></MediaCommentIcon>
          <MediaCommentText>112</MediaCommentText>
        </MediaCard>
        <MediaCard>
          <MediaTitle>aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa</MediaTitle>
          <MediaTime>10:10</MediaTime>
          <MediaDivider></MediaDivider>
          <MediaLikeIcon></MediaLikeIcon>
          <MediaLikeText>1000</MediaLikeText>
          <MediaCommentIcon></MediaCommentIcon>
          <MediaCommentText>112</MediaCommentText>
        </MediaCard>
        <MediaCard>
          <MediaTitle>aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa</MediaTitle>
          <MediaTime>10:10</MediaTime>
          <MediaDivider></MediaDivider>
          <MediaLikeIcon></MediaLikeIcon>
          <MediaLikeText>1000</MediaLikeText>
          <MediaCommentIcon></MediaCommentIcon>
          <MediaCommentText>112</MediaCommentText>
        </MediaCard>
        <MediaCard>
          <MediaTitle>aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa</MediaTitle>
          <MediaTime>10:10</MediaTime>
          <MediaDivider></MediaDivider>
          <MediaLikeIcon></MediaLikeIcon>
          <MediaLikeText>1000</MediaLikeText>
          <MediaCommentIcon></MediaCommentIcon>
          <MediaCommentText>112</MediaCommentText>
        </MediaCard>
      </MediaList>
    </TotalMediaWraper>
  );
}
