/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-2",
    "aws_dynamodb_all_tables_region": "ap-northeast-2",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "users-staging",
            "region": "ap-northeast-2"
        },
        {
            "tableName": "info-staging",
            "region": "ap-northeast-2"
        },
        {
            "tableName": "teamInfo-staging",
            "region": "ap-northeast-2"
        },
        {
            "tableName": "group-staging",
            "region": "ap-northeast-2"
        },
        {
            "tableName": "comment-staging",
            "region": "ap-northeast-2"
        },
        {
            "tableName": "post-staging",
            "region": "ap-northeast-2"
        },
        {
            "tableName": "contents-staging",
            "region": "ap-northeast-2"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "userApi",
            "endpoint": "https://zolorulsoa.execute-api.ap-northeast-2.amazonaws.com/staging",
            "region": "ap-northeast-2"
        },
        {
            "name": "groupApi",
            "endpoint": "https://9dx9n77oc1.execute-api.ap-northeast-2.amazonaws.com/staging",
            "region": "ap-northeast-2"
        },
        {
            "name": "commentApi",
            "endpoint": "https://2gad9kcapa.execute-api.ap-northeast-2.amazonaws.com/staging",
            "region": "ap-northeast-2"
        },
        {
            "name": "postApi",
            "endpoint": "https://mfcoxooq74.execute-api.ap-northeast-2.amazonaws.com/staging",
            "region": "ap-northeast-2"
        }
    ],
    "aws_cognito_region": "ap-northeast-2",
    "aws_user_pools_id": "ap-northeast-2_PWjbHCF0a",
    "aws_user_pools_web_client_id": "bmchqveagd7k1vci9ths6r57r",
    "oauth": {
        "domain": "sport-cog.auth.ap-northeast-2.amazoncognito.com",
        "scope": [
            "aws.cognito.signin.user.admin",
            "email",
            "openid",
            "profile"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "token"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [
        "NAME",
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_UPPERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
